name: Python Application Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install scikit-learn
      run: pip install -r requirements.txt
      
    - name: Execute bcancer.py
      run: python bcancer.py

  job2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Execute test.py
      run: python test.py
